Update flashusb.sh
intel/Edge-Software-Provisioner pull request #26
Opened 2022-01-29 06:21 UTC by zhajianl

Ubuntu 18.04 and latest versions are using bash 4.4.20.
Ubuntu parse usb path is /dev/sda
centos7.9 is using bash 4.2.46(2).
centos parse usb path is \/dev/sda and is invalid.
This issue only happend on centos7.9 and is related with bash version.
In order to compatible both Centos and Ubuntu, we change bash codes for both OS.

This patch is verified on Ubuntu18.04 and centos7.9, both are ok.

2022-01-29 06:25 UTC, sunausti requested changes

2022-01-29 06:25 UTC, sunausti commented on flashusb.sh
> +        USB_DRIVE="${_usb/_${_hex}/}-($_usbpath)"
```suggestion
        USB_DRIVE="${_usb/_${_hex}/}-(${_usbpath})"
```

2022-01-29 06:25 UTC, sunausti commented on flashusb.sh
> +            USB_NAMES="${USB_NAMES} ${_usb/_${_hex}/}-($_usbpath)"
```suggestion
            USB_NAMES="${USB_NAMES} ${_usb/_${_hex}/}-(${_usbpath})"
```

2022-01-29 06:29 UTC, sunausti approved these changes
LGTM @dvintel @brod-intel please help review.

2022-02-03 23:27 UTC, dvintel commented
LGTM, @brod-intel ?

2022-02-04 03:52 UTC, brod-intel commented
LGTM, we'll merge it.

2022-02-09 15:34 UTC, merged